version: "3.9"
services:
  db:
    image: postgres:15
    container_name: wb_scrapper_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
      - .env-non-dev
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: wb_scrapper_redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
      - .env-non-dev

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb_scrapper_bot
    command: sh -c "alembic upgrade head && python -m bot"
    restart: always
    env_file:
      - .env
      - .env-non-dev
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb_scrapper_celery
    command: sh -c "celery -A bot.utils.notifications:celery worker --loglevel=INFO"
    restart: always
    env_file:
      - .env
      - .env-non-dev
    depends_on:
      - bot

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb_scrapper_celery_beat
    command: sh -c "celery -A bot.utils.notifications:celery beat --loglevel=INFO"
    restart: always
    env_file:
      - .env
      - .env-non-dev
    depends_on:
      - bot

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb_scrapper_flower
    command: sh -c "celery -A bot.utils.notifications:celery flower"
    ports:
      - 5555:5555
    restart: always
    env_file:
      - .env
      - .env-non-dev
    depends_on:
      - celery

volumes:
  db_data: